### ISSUE TITLE
could not open input file artisan

### ISSUE THREAD

**Issue by Yanom1212** [JoshuaWalsh/docker-pterodactyl-panel#2]

**Comment by Yanom1212** [comment]
docker-compose :
version: "3.4"
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: admin
      MYSQL_PASSWORD: Bella0228
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    volumes:
      - /volume2/docker/pterodactyl-node/db/:/var/lib/mysql
  cache:
    image: redis
    restart: always
  php-fpm:
    image: joshuawalsh/pterodactyl-panel
    restart: always
    depends_on:
      - database
    volumes:
      - /volume2/docker/pterodactyl-node/app/:/var/www/html/
      - /volume2/docker/pterodactyl-node/storage/:/var/www/html/storage/
      - /volume2/docker/pterodactyl-node/public/:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: admin
      DB_PASSWORD: Bella0228
  nginx:
    image: joshuawalsh/nginx-for-php-fpm
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 5080:80
    volumes:
      - /volume2/docker/pterodactyl-node/public2/:/var/www/html/

**Comment by JoshuaWalsh** [comment]
The php-fpm and nginx containers need to point to the same public directory:

```yaml
version: "3.4"
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
    volumes:
      - /volume2/docker/pterodactyl-node/db/:/var/lib/mysql
  cache:
    image: redis
    restart: always
  php-fpm:
    image: joshuawalsh/pterodactyl-panel
    restart: always
    depends_on:
      - database
    volumes:
      - /volume2/docker/pterodactyl-node/app/:/var/www/html/
      - /volume2/docker/pterodactyl-node/storage/:/var/www/html/storage/
      - /volume2/docker/pterodactyl-node/public/:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: admin
      DB_PASSWORD: Password
  nginx:
    image: joshuawalsh/nginx-for-php-fpm
    restart: always
    depends_on:
      - php-fpm
    ports:
      - 5080:80
    volumes:
      - /volume2/docker/pterodactyl-node/public/:/var/www/html/
```

**Comment by jfgodin** [comment]
I having the same problem but my containers are pointing to the same public directory.

`version: "3.4"
services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - /opt/configs/pterodactyl-db:/var/lib/mysql
  cache:
    image: redis
    restart: unless-stopped
  php-fpm:
    image: joshuawalsh/pterodactyl-panel
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - /mnt/pool/pterodactyl/app:/var/www/html/
      - /mnt/pool/pterodactyl/storage:/var/www/html/storage/
      - /mnt/pool/pterodactyl/public:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3310
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: password
  nginx:
    image: joshuawalsh/nginx-for-php-fpm
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 5080:80
    volumes:
      - /mnt/pool/pterodactyl/public:/var/www/html/

volumes:
  public:
  db:
  storage:
  app:`

**Comment by JoshuaWalsh** [comment]
@jfgodin I haven't been able to reproduce this issue. Could you try doing it using Docker volumes instead of mounts?

```
version: "3.4"
services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis
    restart: unless-stopped
  php-fpm:
    image: joshuawalsh/pterodactyl-panel
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - app:/var/www/html/
      - storage:/var/www/html/storage/
      - public:/var/www/html/public/
    environment:
      DB_HOST: database
      DB_PORT: 3310
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: password
  nginx:
    image: joshuawalsh/nginx-for-php-fpm
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 5080:80
    volumes:
      - public:/var/www/html/

volumes:
  public:
  db:
  storage:
  app:
```

If this helps, the issue might be with file permissions.
